package ctrmap.formats.containers;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;

import ctrmap.LittleEndianDataInputStream;
import ctrmap.LittleEndianDataOutputStream;
import ctrmap.Utils;
import ctrmap.Workspace;
import ctrmap.formats.GameFiles;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.Arrays;
import java.util.UUID;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * Extractor for the generic containers used in 3DS Pokemon games (6 and 7).
 * Generally, those files are generated by gflib_cpp/tools/binlinder.rb,
 * official name is unknown. Often also called Mini packs.
 *
 * <h2>Who hears about a write</h2>
 * A container is HANDED the {@link GameFiles} it reports to. {@link #storeFile}
 * rewrites the container on disk and then tells that object the file was
 * edited, so the next pack writes it back; {@link #getIOFile} writes into its
 * scratch directory. Both used to be fetched from the application's global
 * session holder at the moment of the write, which had two costs: no container
 * could be written in a test without a live workspace installed in the global,
 * and a write made while no workspace was open was recorded nowhere - the edit
 * sat in the extracted file, the pack never picked it up, and nothing said so.
 * Handed its GameFiles, a container reports to the object it was given and can
 * be given a scratch stand-in ({@code ctrmap.tests.FakeGameFiles}) with no
 * workspace open at all; handed null, the handed constructors refuse, because a
 * container nobody will hear from is that silent edit again.
 *
 * <p>TRANSITIONAL: the constructors that take no GameFiles still exist, for the
 * callers that have not yet been handed their own. Each resolves the open game
 * from the global ONCE, when the container is made, and inherits the global's
 * own null when nothing is open - the one place this class still touches the
 * global, and {@code ctrmap.tests.GameFilesSeamTest} names it. Delete them, and
 * the subclasses' matching ones, when the last such caller is migrated.
 */
public abstract class AbstractGamefreakContainer {

	private File f;
	public int len;
	private int[] offsets;
	/** Who hears about a write. Null only through a transitional constructor with no game open. */
	private final GameFiles files;

	public abstract short getHeader();

	/** Opens an existing container that reports its writes to {@code files}. */
	public AbstractGamefreakContainer(File f, GameFiles files) {
		this.files = handed(files);
		open(f);
	}

	/**
	 * Creates an empty container of {@code fileCount} slots at {@code target},
	 * writing its header now; later writes are reported to {@code files}.
	 */
	public AbstractGamefreakContainer(File target, int fileCount, GameFiles files) {
		this.files = handed(files);
		create(target, fileCount);
	}

	/** Transitional: the open game, resolved once here, for a caller not yet handed its own. See the class comment. */
	public AbstractGamefreakContainer(File f) {
		this.files = Workspace.session();
		open(f);
	}

	/** Transitional: the open game, resolved once here, for a caller not yet handed its own. See the class comment. */
	public AbstractGamefreakContainer(File target, int fileCount) {
		this.files = Workspace.session();
		create(target, fileCount);
	}

	/** A handed GameFiles must exist: null here is an edit nobody would ever pack. */
	private static GameFiles handed(GameFiles files) {
		if (files == null) {
			throw new IllegalArgumentException("a container must be handed the GameFiles it reports its"
					+ " writes to; handed null, every edit through it would go unrecorded and unpacked");
		}
		return files;
	}

	private void open(File f) {
		if (f != null) {
			this.f = f;
			verify();
		} else {
			System.err.println("Unable to open file. Expect a crash soon.");
		}
	}

	private void create(File target, int fileCount) {
		this.f = target;
		len = fileCount;
		int headerLength = len * 4 + 8;
		int startingOffset = getIsPadded() ? (int)Math.ceil(headerLength / 128f) * 0x80 : headerLength;
		offsets = new int[len + 1];
		for (int i = 0; i < offsets.length; i++){
			offsets[i] = startingOffset;
			if (getIsPadded()){
				startingOffset += 0x80;
			}
		}
		try {
			LittleEndianDataOutputStream out = new LittleEndianDataOutputStream(new FileOutputStream(target));
			out.write2Bytes(getHeader());
			out.writeShort((short)(len));
			for (int i = 0; i < len + 1; i++) {
				out.writeInt(offsets[i]);
			}
			if (getIsPadded()){
				out.write(Utils.getPadding(0, headerLength));
				out.write(new byte[len * 0x80]);
			}
			out.close();
		} catch (IOException ex) {
			Logger.getLogger(AbstractGamefreakContainer.class.getName()).log(Level.SEVERE, null, ex);
		}
	}

	public boolean verify() {
		try {
			LittleEndianDataInputStream dis = new LittleEndianDataInputStream(new FileInputStream(f));
			if (dis.read2Bytes() != getHeader()) {
				System.err.println("GfContainer header mismatch!");
				System.out.println("Error verifying file " + f.getAbsolutePath());
			}
			len = dis.readShort();
			offsets = new int[len + 1];
			for (int i = 0; i < len + 1; i++) {
				offsets[i] = dis.readInt();
			}
			dis.close();
			return true;
		} catch (IOException e) {
			e.printStackTrace();
			System.out.println("An IOException occured while reading " + f.getName());
			return false;
		}
	}

	public File getOriginFile() {
		return f;
	}

	public int getOffset(int fileNum) {
		return offsets[fileNum];
	}

	public byte[] getFile(int fileNum) {
		try {
			LittleEndianDataInputStream dis = new LittleEndianDataInputStream(new FileInputStream(f));
			dis.skip(offsets[fileNum]);
			byte[] b = new byte[offsets[fileNum + 1] - offsets[fileNum]];
			dis.read(b);
			dis.close();
			return b;
		} catch (IOException e) {
			Logger.getLogger(AbstractGamefreakContainer.class.getName()).log(Level.SEVERE, null, e);
			return null;
		}
	}

	/**
	 * One subfile written out to a fresh file in the handed scratch directory,
	 * or null when it could not be written - including when this container was
	 * made through a transitional constructor with no game open, which is the
	 * same null a missing temp folder produced before.
	 */
	public File getIOFile(int fileNum){
		if (files == null) {
			return null;
		}
		try {
			byte[] b = getFile(fileNum);
			File out = new File(files.scratch(), "agfc_extract_" + UUID.randomUUID().toString());
			OutputStream os = new FileOutputStream(out);
			os.write(b);
			os.close();
			return out;
		} catch (IOException ex) {
			return null;
		}
	}

	public boolean checkStoreStatus(int num, byte[] data) {
		return !Arrays.equals(data, getFile(num));
	}

	public abstract ContentType getDefaultContentType(int index);

	public abstract boolean getIsPadded();

	/**
	 * Stores a subfile, rewriting the container on disk and reporting the file
	 * as edited to the handed {@link GameFiles}. Returns true when the
	 * container ends up holding the given data (including the no-op case where
	 * it already did), false when the write failed - callers that must not
	 * report a failed write as success have to check this.
	 */
	public boolean storeFile(int num, byte[] data) {
		byte[] paddedData;
		if (getIsPadded()){
			byte[] padding = Utils.getPadding(getOffset(num), data.length);
			paddedData = new byte[data.length + padding.length];
			System.arraycopy(data, 0, paddedData, 0, data.length);
			System.arraycopy(padding, 0, paddedData, data.length, padding.length);
		}
		else {
			paddedData = data;
		}
		if (!checkStoreStatus(num, paddedData)){
			return true;
		}
		try {
			int pos = 0;
			LittleEndianDataInputStream dis = new LittleEndianDataInputStream(new FileInputStream(f));
			byte[] b = new byte[dis.available()];
			dis.read(b);
			dis.close();
			//calculate new offsets
			int change = paddedData.length - (offsets[num + 1] - offsets[num]);
			for (int i = num + 1; i < len + 1; i++) {
				offsets[i] += change;
			}
			LittleEndianDataOutputStream out = new LittleEndianDataOutputStream(new FileOutputStream(f));
			out.write2Bytes(getHeader());
			out.writeShort((short) len);
			pos += 4;
			for (int i = 0; i < offsets.length; i++) {
				out.writeInt(offsets[i]);
				pos += 4;
			}
			while (pos < offsets[0]) {
				out.write(0);
				pos++;
			}
			int firstlen = offsets[num] - offsets[0];
			if (firstlen > 0) {
				byte[] bytesbefore = new byte[firstlen];
				System.arraycopy(b, offsets[0], bytesbefore, 0, firstlen);
				out.write(bytesbefore);
			}
			out.write(paddedData);
			int secondlen = offsets[len] - offsets[num + 1];
			if (secondlen > 0) {
				byte[] bytesafter = new byte[secondlen];
				System.arraycopy(b, offsets[num + 1] - change, bytesafter, 0, secondlen);
				out.write(bytesafter);
			}
			out.flush();
			out.close();
			//null only through a transitional constructor with no game open,
			//where the global's own addPersist was a no-op as well
			if (files != null) {
				files.edited(getOriginFile());
			}
			return true;
		} catch (IOException e) {
			e.printStackTrace();
			System.out.println("An IOException occured while writing " + f.getName());
			return false;
		}
	}

	public boolean storeFile(int num, File f){
		try {
			InputStream in = new FileInputStream(f);
			byte[] b = new byte[in.available()];
			in.read(b);
			boolean ok = storeFile(num, b);
			in.close();
			return ok;
		} catch (IOException ex) {
			Logger.getLogger(AbstractGamefreakContainer.class.getName()).log(Level.SEVERE, null, ex);
			return false;
		}
	}
}
