package ctrmap.formats.containers;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;

import ctrmap.LittleEndianDataInputStream;
import ctrmap.LittleEndianDataOutputStream;
import ctrmap.formats.GameFiles;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.Arrays;
import java.util.UUID;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * Extractor for the generic containers used in 3DS Pokemon games (6 and 7).
 * Generally, those files are generated by gflib_cpp/tools/binlinder.rb,
 * official name is unknown. Often also called Mini packs.
 *
 * <h2>Who hears about a write</h2>
 * A container is HANDED the {@link GameFiles} it reports to. {@link #storeFile}
 * rewrites the container on disk and then tells that object the file was
 * edited, so the next pack writes it back; {@link #getIOFile} writes into its
 * scratch directory. Both used to be fetched from the application's global
 * session holder at the moment of the write, which had two costs: no container
 * could be written in a test without a live workspace installed in the global,
 * and a write made while no workspace was open was recorded nowhere - the edit
 * sat in the extracted file, the pack never picked it up, and nothing said so.
 * Handed its GameFiles, a container reports to the object it was given and can
 * be given a scratch stand-in ({@code ctrmap.tests.FakeGameFiles}) with no
 * workspace open at all; handed null, the constructors refuse, because a
 * container nobody will hear from is that silent edit again.
 *
 * <p>There is no constructor that takes no GameFiles. There were, while the
 * callers were being migrated: each resolved the open game from the
 * application's global once, when the container was made, and inherited the
 * global's own null when nothing was open, so a container made with no
 * workspace wrote edits nobody packed and extracted subfiles nowhere.
 * {@code ctrmap.tests.GameFilesSeamTest} holds the format layer to reaching
 * that global nowhere at all; a constructor that fetched it would be counted.
 */
public abstract class AbstractGamefreakContainer {

	private File f;
	public int len;
	private int[] offsets;
	/** Who hears about a write. Never null: the constructors refuse null. */
	private final GameFiles files;

	public abstract short getHeader();

	/** Opens an existing container that reports its writes to {@code files}. */
	public AbstractGamefreakContainer(File f, GameFiles files) {
		this.files = handed(files);
		open(f);
	}

	/**
	 * Creates an empty container of {@code fileCount} slots at {@code target},
	 * writing its header now; later writes are reported to {@code files}.
	 */
	public AbstractGamefreakContainer(File target, int fileCount, GameFiles files) {
		this.files = handed(files);
		create(target, fileCount);
	}

	/** A handed GameFiles must exist: null here is an edit nobody would ever pack. */
	private static GameFiles handed(GameFiles files) {
		if (files == null) {
			throw new IllegalArgumentException("a container must be handed the GameFiles it reports its"
					+ " writes to; handed null, every edit through it would go unrecorded and unpacked");
		}
		return files;
	}

	/**
	 * Opens the file, or refuses to be a container at all.
	 *
	 * <p>It used to call {@link #verify} and ignore the answer, and the old verify could
	 * not say no anyway - so the wrong file, or a torn one, produced an object every
	 * caller treated as real. "Expect a crash soon" was printed to stderr where nobody
	 * runs the program from a console, and the crash, when it came, named a line a long
	 * way from the file that caused it.
	 */
	private void open(File f) {
		if (f == null) {
			throw new IllegalArgumentException("a container must be opened on a file, not null");
		}
		this.f = f;
		if (!verify()) {
			throw new IllegalStateException(whyNot == null
				? f.getName() + " is not a readable " + getClass().getSimpleName() : whyNot);
		}
	}

	private void create(File target, int fileCount) {
		this.f = target;
		len = fileCount;
		int headerLength = len * 4 + 8;
		int startingOffset = getIsPadded() ? (int)Math.ceil(headerLength / 128f) * 0x80 : headerLength;
		offsets = new int[len + 1];
		for (int i = 0; i < offsets.length; i++){
			offsets[i] = startingOffset;
			if (getIsPadded()){
				startingOffset += 0x80;
			}
		}
		try {
			LittleEndianDataOutputStream out = new LittleEndianDataOutputStream(new FileOutputStream(target));
			out.write2Bytes(getHeader());
			out.writeShort((short)(len));
			for (int i = 0; i < len + 1; i++) {
				out.writeInt(offsets[i]);
			}
			if (getIsPadded()){
				out.write(ctrmap.util.Bytes.getPadding(0, headerLength));
				out.write(new byte[len * 0x80]);
			}
			out.close();
		} catch (IOException ex) {
			Logger.getLogger(AbstractGamefreakContainer.class.getName()).log(Level.SEVERE, null, ex);
		}
	}

	/**
	 * Whether this file really is one of these containers, and why not when it is not.
	 *
	 * <p>IT COULD NOT SAY NO. The header check printed "GfContainer header mismatch!" to
	 * stderr and then returned true, so pointing any container constructor at the wrong
	 * file - a GARC, a BCH, a half-written temp file - produced an object the rest of the
	 * editor treated as a zone or an area, reading subfile bounds out of whatever those
	 * bytes happened to be. It also accepted offsets that run past the end of the file,
	 * which is what a truncated or torn container looks like.
	 *
	 * <p>{@link #whyNot} carries the reason, so a caller can report what the user needs
	 * to hear rather than "could not open".
	 */
	public boolean verify() {
		whyNot = null;
		try {
			long onDisk = f.length();
			LittleEndianDataInputStream dis = new LittleEndianDataInputStream(new FileInputStream(f));
			try {
				short head = dis.read2Bytes();
				if (head != getHeader()) {
					whyNot = f.getName() + " is not a " + getClass().getSimpleName()
						+ ": its first two bytes are 0x" + Integer.toHexString(head & 0xFFFF)
						+ " and this container is 0x" + Integer.toHexString(getHeader() & 0xFFFF) + ".";
					return false;
				}
				len = dis.readShort();
				if (len < 0) {
					whyNot = f.getName() + " declares " + len + " subfiles.";
					return false;
				}
				offsets = new int[len + 1];
				for (int i = 0; i < len + 1; i++) {
					offsets[i] = dis.readInt();
				}
			} finally {
			}
			dis.close();
			//THE OFFSETS MUST FIT IN THE FILE. A container whose last offset is past the end
			//is truncated, and every read from it would have come back zero-padded and been
			//reported as data - which is how a torn pack becomes a zone full of nothing.
			for (int i = 0; i <= len; i++) {
				if (offsets[i] < 0 || offsets[i] > onDisk) {
					whyNot = f.getName() + " is truncated or damaged: subfile " + i + " starts at 0x"
						+ Integer.toHexString(offsets[i]) + " and the file is only " + onDisk
						+ " byte(s) long.";
					return false;
				}
				if (i > 0 && offsets[i] < offsets[i - 1]) {
					whyNot = f.getName() + " is damaged: subfile " + i + " starts before subfile "
						+ (i - 1) + " does.";
					return false;
				}
			}
			return true;
		} catch (IOException e) {
			whyNot = "could not read " + f.getName() + ": " + ctrmap.util.Bytes.reason(e);
			return false;
		}
	}

	/** Why {@link #verify} said no, or null when it said yes. */
	public String whyNot() {
		return whyNot;
	}

	private String whyNot;

	public File getOriginFile() {
		return f;
	}

	public int getOffset(int fileNum) {
		return offsets[fileNum];
	}

	/**
	 * One subfile, whole, or null - never part of one padded out with zeros.
	 *
	 * <p>IT USED TO ZERO-FILL AND CALL THAT SUCCESS. {@code skip} and {@code read} both
	 * return how much they actually managed, and both results were dropped, so a file
	 * shorter than its own offset table handed back a buffer of exactly the right length
	 * whose tail was zeros. Measured on a GARC truncated to half its size: 278 of 431
	 * entries came back pure zero, none null, no exception, no log line. Downstream that
	 * is a zone with no entities, an area with no atmosphere, a region with no geometry -
	 * and then the editor writes that back over the real thing.
	 */
	public byte[] getFile(int fileNum) {
		if (offsets == null || fileNum < 0 || fileNum + 1 >= offsets.length) {
			return null;
		}
		int want = offsets[fileNum + 1] - offsets[fileNum];
		if (want < 0) {
			return null;
		}
		try {
			LittleEndianDataInputStream dis = new LittleEndianDataInputStream(new FileInputStream(f));
			try {
				byte[] b = new byte[want];
				//BOTH OF THESE REFUSE SHORT DATA. skip() and read() answer how much they managed
				//and both answers used to be dropped, which is how a truncated file became a
				//zero-filled buffer reported as the subfile.
				dis.skipFully(offsets[fileNum]);
				dis.readFully(b);
				return b;
			} finally {
				dis.close();
			}
		} catch (IOException e) {
			Logger.getLogger(AbstractGamefreakContainer.class.getName()).log(Level.SEVERE,
				"reading " + f + " subfile " + fileNum, e);
			return null;
		}
	}

	/**
	 * One subfile written out to a fresh file in the handed scratch directory,
	 * or null when it could not be written.
	 */
	public File getIOFile(int fileNum){
		try {
			byte[] b = getFile(fileNum);
			File out = new File(files.scratch(), "agfc_extract_" + UUID.randomUUID().toString());
			OutputStream os = new FileOutputStream(out);
			os.write(b);
			os.close();
			return out;
		} catch (IOException ex) {
			return null;
		}
	}

	public boolean checkStoreStatus(int num, byte[] data) {
		return !Arrays.equals(data, getFile(num));
	}

	public abstract ContentType getDefaultContentType(int index);

	public abstract boolean getIsPadded();

	/**
	 * Stores a subfile, rewriting the container on disk and reporting the file as edited
	 * to the handed {@link GameFiles}. Returns NOTHING; a write that failed THROWS.
	 *
	 * <p>IT USED TO RETURN FALSE, and twelve callers dropped the answer - two of them in
	 * the fog editor, one statement before telling the user the atmosphere was saved.
	 * The failure this is documented against is an emulator or a virus scanner holding
	 * the archive open, which is a thing that happens to this project's users, and the
	 * result was a dialog reporting a save of bytes that were never written.
	 *
	 * <p>A boolean nobody is obliged to read is a convention. This throws, so the only
	 * way to carry on past a failed write is a catch somebody wrote on purpose - and the
	 * UI paths already report a thrown exception through {@code Ui.error}.
	 *
	 * <p>AND IT RETURNS VOID, because keeping the boolean "so the callers that check
	 * still compile" is what made the next defect. Twelve of those checks could no
	 * longer fail, and two of them held the only refusal that named what the user was
	 * editing - "could not write region 153", "could not write area 21 subfile 11" -
	 * so the message became a temp path and a subfile number. A boolean that can only
	 * be true is a trap with an invitation attached; void turns every {@code if
	 * (!storeFile(...))} into a compile error instead, and the callers that want their
	 * own name on the failure catch this and say so with the cause attached.
	 */
	public void storeFile(int num, byte[] data) {
		byte[] paddedData;
		if (getIsPadded()){
			byte[] padding = ctrmap.util.Bytes.getPadding(getOffset(num), data.length);
			paddedData = new byte[data.length + padding.length];
			System.arraycopy(data, 0, paddedData, 0, data.length);
			System.arraycopy(padding, 0, paddedData, data.length, padding.length);
		}
		else {
			paddedData = data;
		}
		if (!checkStoreStatus(num, paddedData)){
			return;
		}
		try {
			int pos = 0;
			//THE WHOLE CONTAINER, OR NONE OF IT. storeFile rebuilds the file from this buffer,
			//so a short read here writes zeros over every subfile the user did NOT edit -
			//the zone header, the region model, the collision - and reports a successful
			//save.
			byte[] b = java.nio.file.Files.readAllBytes(f.toPath());
			//calculate new offsets
			int change = paddedData.length - (offsets[num + 1] - offsets[num]);
			for (int i = num + 1; i < len + 1; i++) {
				offsets[i] += change;
			}
			LittleEndianDataOutputStream out = new LittleEndianDataOutputStream(new FileOutputStream(f));
			out.write2Bytes(getHeader());
			out.writeShort((short) len);
			pos += 4;
			for (int i = 0; i < offsets.length; i++) {
				out.writeInt(offsets[i]);
				pos += 4;
			}
			while (pos < offsets[0]) {
				out.write(0);
				pos++;
			}
			int firstlen = offsets[num] - offsets[0];
			if (firstlen > 0) {
				byte[] bytesbefore = new byte[firstlen];
				System.arraycopy(b, offsets[0], bytesbefore, 0, firstlen);
				out.write(bytesbefore);
			}
			out.write(paddedData);
			int secondlen = offsets[len] - offsets[num + 1];
			if (secondlen > 0) {
				byte[] bytesafter = new byte[secondlen];
				System.arraycopy(b, offsets[num + 1] - change, bytesafter, 0, secondlen);
				out.write(bytesafter);
			}
			out.flush();
			out.close();
			files.edited(getOriginFile());
		} catch (IOException e) {
			//THROWN, not returned: see the javadoc. The message names the file and the
			//subfile, because "could not write" with no name is what the user used to get
			//on a console they do not have.
			throw new IllegalStateException("could not write subfile " + num + " of "
				+ f.getName() + ": " + ctrmap.util.Bytes.reason(e), e);
		}
	}

	/**
	 * The same store, reading the bytes out of a file first.
	 *
	 * <p>IT LOGGED AND ANSWERED FALSE, which is the import path in the archive
	 * browser: a file that could not be read got a line on a console the user does not
	 * have and a false nobody downstream distinguished from "the container refused".
	 * It throws like the other one now, naming both files.
	 */
	public void storeFile(int num, File f) {
		try {
			storeFile(num, java.nio.file.Files.readAllBytes(f.toPath()));
		} catch (IOException cannotRead) {
			throw new IllegalStateException("could not read " + f.getName() + " to store it as"
				+ " subfile " + num + " of " + getOriginFile().getName() + ": "
				+ ctrmap.util.Bytes.reason(cannotRead), cannotRead);
		}
	}
}
