package ctrmap.tools;

import ctrmap.formats.garc.GARC;
import ctrmap.formats.garc.LZ11;
import ctrmap.formats.h3d.BCHFile;
import ctrmap.formats.h3d.BchMapModel;
import ctrmap.formats.h3d.texturing.H3DTexture;
import ctrmap.formats.tilemap.TilePalette;
import java.io.File;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;

/**
 * Measures, for every material a terrain brush could match by name, how much of
 * its base texture is actually opaque.
 *
 * <p>Why: the tile painter picks the mesh to paint into by substring-matching
 * the brush's hints against the map's own material names, and a name cannot
 * tell a tiling GROUND texture from a SPRITE ATLAS. On Route 102 that matched
 * the brush "rock" to {@code chip_jump_gake} - the jump-down ledge sprite strip,
 * nearly half transparent - and "path" to {@code chip_wood_b}, the map's
 * decoration atlas of bushes and flowers. The painted floor then sampled empty
 * texels and drew nothing, over ground the compositor had already clipped away:
 * a black hole where the player was standing.
 *
 * <p>Opacity is the signal a name cannot carry, so it gets measured once here
 * and written to {@code oras_ground_materials.tsv}, which
 * {@link ctrmap.formats.tilemap.PaintedRegionBuilder} consults before accepting
 * one of the map's own materials. Materials that fail are not banned from the
 * editor - the brush falls through to {@link ctrmap.formats.tilemap.TerrainCatalog},
 * which imports a curated opaque donor instead.
 *
 * <p>Args: FieldData (a/0/3/9), AreaData (a/0/1/4), ZoneData (a/0/1/3), output TSV.
 */
public class GroundMaterialAudit {

	/** Per material name, aggregated over every place it appears. */
	static class Stat {

		String texture;
		long opaque;
		long total;
		int occurrences;
		double worstOpaqueFrac = 1.0;
	}

	public static void main(String[] args) throws Exception {
		if (args.length < 5) {
			System.out.println("usage: GroundMaterialAudit <FieldData GARC> <AreaData GARC> <ZoneData GARC>"
					+ " <MapMatrix GARC> <out.tsv>");
			System.exit(1);
		}
		GARC fd = new GARC(new File(args[0]));
		GARC ad = new GARC(new File(args[1]));
		GARC zd = new GARC(new File(args[2]));
		GARC mm = new GARC(new File(args[3]));
		String outPath = args[4];

		//which areas each region belongs to: walk the zones' area ids and their
		//matrices' region grids (a region can appear under more than one area)
		byte[] master = zd.getDecompressedEntry(zd.length - 2);
		Map<Integer, List<Integer>> areasOfRegion = new HashMap<>();
		for (int zone = 0; zone < master.length / 0x38; zone++) {
			int area = u16(master, zone * 0x38 + 2);
			int matIdx = u16(master, zone * 0x38 + 4);
			if (matIdx >= mm.length) {
				continue;
			}
			byte[] mat = mm.getDecompressedEntry(matIdx);
			int sub0 = u32(mat, 4);
			int w = u16(mat, sub0 + 4), h = u16(mat, sub0 + 6);
			for (int k = 0; k < w * h; k++) {
				int rid = u16(mat, sub0 + 8 + k * 2);
				if (rid == 0xFFFF) {
					continue;
				}
				List<Integer> l = areasOfRegion.get(rid);
				if (l == null) {
					areasOfRegion.put(rid, l = new ArrayList<>());
				}
				if (!l.contains(area)) {
					l.add(area);
				}
			}
		}

		//alpha stats per texture name, per area (decoded once)
		Map<Integer, Map<String, double[]>> areaTex = new HashMap<>();
		Map<String, Stat> stats = new TreeMap<>();

		int scanned = 0;
		for (Map.Entry<Integer, List<Integer>> e : areasOfRegion.entrySet()) {
			int region = e.getKey();
			if (region >= fd.length) {
				continue;
			}
			byte[] model;
			try {
				model = sub(fd.getDecompressedEntry(region), 1);
			} catch (RuntimeException ex) {
				continue;
			}
			if (model == null || !BchMapModel.isMapModel(model)) {
				continue;
			}
			Map<String, String> matToTex = materialTextures(model);
			if (matToTex.isEmpty()) {
				continue;
			}
			scanned++;
			for (int area : e.getValue()) {
				Map<String, double[]> tex = areaTex.get(area);
				if (tex == null) {
					areaTex.put(area, tex = textureAlpha(ad, area));
				}
				for (Map.Entry<String, String> mt : matToTex.entrySet()) {
					if (!interesting(mt.getKey())) {
						continue;
					}
					double[] a = tex.get(mt.getValue());
					if (a == null) {
						continue;
					}
					Stat s = stats.get(mt.getKey());
					if (s == null) {
						stats.put(mt.getKey(), s = new Stat());
						s.texture = mt.getValue();
					}
					s.opaque += (long) a[0];
					s.total += (long) a[1];
					s.occurrences++;
					s.worstOpaqueFrac = Math.min(s.worstOpaqueFrac, a[1] > 0 ? a[0] / a[1] : 1.0);
				}
			}
		}

		try (PrintWriter pw = new PrintWriter(outPath, "UTF-8")) {
			pw.println("# Ground-material opacity - generated by ctrmap.tools.GroundMaterialAudit.");
			pw.println("# A terrain brush may only paint into one of the map's OWN materials when");
			pw.println("# that material's texture is essentially opaque. Transparent ones are sprite");
			pw.println("# strips and decoration atlases: painting a floor with them draws nothing.");
			pw.println("# material\ttexture\toccurrences\tworstOpaquePercent");
			for (Map.Entry<String, Stat> s : stats.entrySet()) {
				pw.printf("%s\t%s\t%d\t%.2f%n", s.getKey(), s.getValue().texture,
						s.getValue().occurrences, s.getValue().worstOpaqueFrac * 100.0);
			}
		}

		//report the distribution so the threshold is chosen from data
		double[] fr = new double[stats.size()];
		int i = 0;
		for (Stat s : stats.values()) {
			fr[i++] = s.worstOpaqueFrac * 100.0;
		}
		Arrays.sort(fr);
		System.out.println("regions scanned " + scanned + ", brush-matchable materials " + stats.size());
		if (fr.length > 0) {
			System.out.printf("worst-opaque%% distribution: min %.1f  p10 %.1f  p25 %.1f  median %.1f  p75 %.1f  max %.1f%n",
					fr[0], fr[fr.length / 10], fr[fr.length / 4], fr[fr.length / 2], fr[fr.length * 3 / 4], fr[fr.length - 1]);
			int[] buckets = new int[11];
			for (double f : fr) {
				buckets[Math.min(10, (int) (f / 10))]++;
			}
			for (int b = 0; b < 11; b++) {
				if (buckets[b] > 0) {
					System.out.printf("  %3d-%3d%% opaque: %4d materials%n", b * 10, Math.min(100, b * 10 + 9), buckets[b]);
				}
			}
		}
		System.out.println("wrote " + outPath);
	}

	/** True when any terrain brush hint can substring-match this material name. */
	private static boolean interesting(String name) {
		String n = name.toLowerCase();
		for (TilePalette t : TilePalette.values()) {
			for (String hint : t.matHints) {
				if (n.contains(hint)) {
					return true;
				}
			}
		}
		return false;
	}

	/** material name -&gt; its base (slot 0) texture name, read from the model header. */
	private static Map<String, String> materialTextures(byte[] model) {
		Map<String, String> out = new LinkedHashMap<>();
		try {
			BCHFile bch = new BCHFile(model);
			if (bch.errorlevel != 0 || bch.models.isEmpty()) {
				return out;
			}
			for (ctrmap.formats.h3d.texturing.H3DMaterial m : bch.models.get(0).materials) {
				if (m != null && m.name != null && m.name0 != null) {
					out.put(m.name, m.name0);
				}
			}
		} catch (RuntimeException ex) {
			//unparsable model: contributes nothing
		}
		return out;
	}

	/** texture name -&gt; {opaqueTexels, totalTexels} for one area's world texture pack. */
	private static Map<String, double[]> textureAlpha(GARC adGarc, int area) {
		Map<String, double[]> out = new HashMap<>();
		try {
			byte[] wTex = sub(adGarc.getDecompressedEntry(area), 11); //AD subfile 11 = world textures
			if (wTex == null || wTex.length < 4) {
				return out;
			}
			if ((wTex[0] & 0xFF) == 0x11) {
				wTex = LZ11.decompress(wTex);
			}
			BCHFile bch = new BCHFile(wTex);
			if (bch.errorlevel != 0) {
				return out;
			}
			for (H3DTexture t : bch.textures) {
				if (t.textureData == null || t.textureSize == null) {
					continue;
				}
				int w = t.textureSize.width, h = t.textureSize.height;
				if (w <= 0 || h <= 0 || t.textureData.length < w * h * 4) {
					continue;
				}
				long opaque = 0;
				for (int p = 3; p < w * h * 4; p += 4) {
					if ((t.textureData[p] & 0xFF) >= 250) {
						opaque++;
					}
				}
				out.put(t.textureName, new double[]{opaque, (double) w * h});
			}
		} catch (RuntimeException ex) {
			//area without a usable texture pack
		}
		return out;
	}

	private static byte[] sub(byte[] c, int i) {
		int o0 = u32(c, 4 + i * 4), o1 = u32(c, 4 + (i + 1) * 4);
		if (o0 < 0 || o1 > c.length || o1 <= o0) {
			return null;
		}
		return Arrays.copyOfRange(c, o0, o1);
	}

	private static int u16(byte[] b, int o) {
		return (b[o] & 0xFF) | ((b[o + 1] & 0xFF) << 8);
	}

	private static int u32(byte[] b, int o) {
		return (b[o] & 0xFF) | ((b[o + 1] & 0xFF) << 8) | ((b[o + 2] & 0xFF) << 16) | ((b[o + 3] & 0xFF) << 24);
	}
}

