package ctrmap.humaninterface;

import ctrmap.CtrmapMainframe;
import java.awt.Dialog;
import java.awt.GraphicsEnvironment;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.TimeUnit;
import javax.swing.JDialog;

/**
 * Modal dialog with a progress bar suitable for SwingWorkers.
 *
 * <p>With no screen there is no window - {@code new JDialog()} throws
 * HeadlessException - but the work behind the bar is not progress UI, it is the
 * pack, the zone load and the archive rewrite themselves, and every report
 * those make on failure lives on the far side of this dialog. Refusing to
 * exist without a display put all of them out of reach of any guard: a suite
 * could not so much as enter {@link ctrmap.Workspace#packWorkspace}. So a
 * headless instance keeps the bar and the label (plain Swing components, which
 * need no peer) and drops only the window, and {@link #showDialog} still waits
 * for {@link #close} the way a modal dialog does, so the order of what happens
 * is the same either way. With a display, nothing here behaves differently.
 */
public class LoadingDialog extends javax.swing.JPanel {

	/**
	 * Creates new form LoadingDialog
	 */
	private JDialog dlg;

	/** Stands in for the modal window's blocking when there is no window. */
	private final CountDownLatch closed = new CountDownLatch(1);

	public LoadingDialog() {
		initComponents();
	}

	public void setDescription(String text) {
		desc.setText(text);
	}

	public void setBarPercent(int val) {
		bar.setValue(val);
	}

	public void close() {
		closed.countDown();
		if (dlg == null) {
			return;
		}
		dlg.dispose();
		dlg.setVisible(false);
	}

	public static LoadingDialog makeDialog(String desc) {
		LoadingDialog ret = new LoadingDialog();
		if (!GraphicsEnvironment.isHeadless()) {
			ret.dlg = new JDialog();
			ret.dlg.add(ret);
		}
		ret.setDescription(desc);
		ret.setBarPercent(0);
		if (ret.dlg != null) {
			ret.dlg.setUndecorated(true);
			ret.dlg.setModalityType(Dialog.ModalityType.APPLICATION_MODAL);
			ret.dlg.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
			ret.dlg.pack();
		}
		return ret;
	}

	public void showDialog() {
		if (dlg == null) {
			//the caller expects to be held here until the worker's done() has
			//closed this, because everything it does next assumes that. The
			//timeout is a backstop against a worker that never finishes: a test
			//run that stops is a result, one that hangs is not.
			try {
				closed.await(2, TimeUnit.MINUTES);
			} catch (InterruptedException ex) {
				Thread.currentThread().interrupt();
			}
			return;
		}
		if (CtrmapMainframe.frame != null) {
			dlg.setLocationRelativeTo(CtrmapMainframe.frame);
		}
		dlg.setVisible(true);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bar = new javax.swing.JProgressBar();
        desc = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setMinimumSize(new java.awt.Dimension(186, 75));

        desc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        desc.setText("Sample text");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(desc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(desc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar bar;
    private javax.swing.JLabel desc;
    // End of variables declaration//GEN-END:variables
}
